In [3]:
import numpy as np

In [3]:
n1 = np.array([1,2,3,4,5,6])  ## creating 1-D array
print(n1)

[1 2 3 4 5 6]


In [7]:
n2 = np.array([[2,3,4,5,6],[1,2,3,4,5]]) ##creating 2-D array
print(n2)

[[2 3 4 5 6]
 [1 2 3 4 5]]


In [11]:
n3 = np.zeros((2,3)) ##initializing numpy array with zero
print(n3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
n4 = np.full((3,3),4)  ##initializing numpy with same number
print(n4)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [19]:
n5 = np.arange(5,15,5)  ##initializing numpy within a range

In [21]:
print(n5)

[ 5 10]


In [23]:
n6 = np.random.randint(1,100,3)  ##initializing numpy array with random number

In [25]:
print(n6)

[20 99 91]


In [27]:
n6.shape

(3,)

In [29]:
n4.shape

(3, 3)

In [31]:
n1.shape

(6,)

In [33]:
n1 = np.random.randint(1,100,5)
n2 = np.random.randint(1,100,5)

In [35]:
print(n1)
print(n2)

[91 25 26 55 52]
[43 80 28 87 38]


In [39]:
np.vstack((n1,n2)) ## joining numpy arary n1 and n2 vertically

array([[91, 25, 26, 55, 52],
       [43, 80, 28, 87, 38]])

In [41]:
np.hstack((n1,n2))   ## joining numpy array n1 and n2 horizontally

array([91, 25, 26, 55, 52, 43, 80, 28, 87, 38])

In [43]:
np.column_stack((n1,n2))  ## joining using column stack

array([[91, 43],
       [25, 80],
       [26, 28],
       [55, 87],
       [52, 38]])

In [45]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [47]:
np.setdiff1d(n1,n2)

array([25, 26, 52, 55, 91])

In [49]:
np.setdiff1d(n2,n1)

array([28, 38, 43, 80, 87])

In [57]:
n3 = np.array([1,2,3,4])
n4 = np.array([1,2,3,4])
np.sum([n3,n4])

20

In [59]:
np.sum([n3,n4],axis = 1)

array([10, 10])

In [61]:
np.sum([n3,n4],axis = 0)

array([2, 4, 6, 8])

In [63]:
## Numpy Math function


In [69]:
##Mean
np.mean(n3)


2.5

In [71]:
np.std(n3)



1.118033988749895

In [73]:
np.median(n3)

2.5

In [11]:
a = np.arange(1,5).reshape(2,2)
a


array([[1, 2],
       [3, 4]])

In [13]:
a = np.arange(1,10).reshape(3,3)

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n1 = np.arange(1,10).reshape(3,3)
n2 = np.arange(11,20).reshape(3,3)

In [27]:
n1
n2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [29]:
n2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [31]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
np.hstack((n1,n2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [39]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [49]:
np.hsplit(a,1)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [51]:
a= np.arange(0,20).reshape(10,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [55]:
np.vsplit(a,2)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])]

In [57]:
np.hsplit(a,2)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14],
        [16],
        [18]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])]

In [59]:
result = np.vsplit(a,2)
result[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
result = np.hsplit(a,2)
result[1]

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])